### ISSUE TITLE
[Bug] Zygisk LSPosed shrinking space below GBoard

### ISSUE THREAD

**Issue by shaunkleyn** [LSPosed/LSPosed#1743]
### Steps to reproduce/复现步骤

1. Tap a text field to open GBoard. Notice the space below GBoard.
2. Install Zygisk LSPosed.
3. Reboot.
4. Tap on a text field to open GBoard. Notice the space is much smaller.

### Expected behaviour/预期行为

Should not affect spacing between the keyboard and bottom of the screen.

### Actual behaviour/实际行为

Space between GBoard and the bottom of the screen decreases making it very difficult to click the arrow that hides /collapses the keyboard.

### Xposed Module List/Xposed 模块列表

```shell
No modules need to be installed for this behavior but these are the modules I have installed:
AllTrans 1.9.5 by akhil.alltrans
Automatic Advanced Settings Expander v1.0 - binarynoise
Disable-FLAG_SECURE v2.0.0 by VarunS2002
Killergram v22.01.17 by Shatyuka
MinMinGuard v2.1.1
Sim Number Setter v1.0 
TwiFucker v1.1 by Dr-TSNG
AdBlocker Reborn v 1.8.2 [Disabled]
Dark Tricks 2.20 [Disabled]
Lucky*Patcher 9.7.0 [Disabled]
```

### Magisk Module List/Magisk 模块列表

```shell
Advanced Charging Controller (ACC) v2022.2.22.1 by VR25
Daily Job Scheduler (DJS) v2021.12.14 by VR25
Magisk Bootloop Protector v1.5 by HuskyDG
Systemless Hosts 1.0 by Magisk
Universal SafetyNet Fix v2.2.1 by kdragOn
Zygisk - LSPosed v1.7.2 (6442) by LSPosed Developers
```

### LSPosed version/LSPosed 版本

1.7.2 (6442)

### Android version/Android 版本

12

### Magisk version/Magisk 版本

7cfce9ff (24201)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[dmesg.txt](https://github.com/LSPosed/LSPosed/files/8190333/dmesg.txt)
[magisk (1).log](https://github.com/LSPosed/LSPosed/files/8190334/magisk.1.log)
[LSPosed_2022-03-05T12_27_14.244.zip](https://github.com/LSPosed/LSPosed/files/8195978/LSPosed_2022-03-05T12_27_14.244.zip)

**Comment by yujincheng08** [comment]
Stop spamming. You didn't strictly follow the issue template.

**Comment by shaunkleyn** [comment]
I attached additional logs this time which is WHY I resubmitted.  I'm not spamming you, I'm not a spammer!!!

**Comment by shaunkleyn** [comment]
It takes time to enter all the information, I'm not doing it just because I'm bored, I'm doing to log a bug!!!

**Comment by yujincheng08** [comment]
> I am using latest debug CI version of LSPosed and enable verbose log

You are not.

**Comment by yujincheng08** [comment]
> For usage issues, please provide the log zip saved from manager; for activation issues, please provide [bugreport](https://developer.android.com/studio/debug/bug-report).

You are not.

**Comment by shaunkleyn** [comment]
> > I am using latest debug CI version of LSPosed and enable verbose log
> 
> You are not.

I'm using 1.7.2 (6442) which I suspected is newer than 1.7.2 (6379).  (Because 6442 is greater than 6379).
Under LSPosed settings, the switch next to "Disable verbose log" is unchecked, which means verbose log is enabled.


> > For usage issues, please provide the log zip saved from manager; for activation issues, please provide [bugreport](https://developer.android.com/studio/debug/bug-report).
> 
> You are not.

I would have thought this is a usage issue which is why I'm providing logs from manager.

But, not to worry, I won't log it again.  It'd be easier and less frustrating for both of us if I just live with the issue and not report it.

Thanks for your help anyway.

**Comment by yujincheng08** [comment]
> I'm using 1.7.2 (6442) which I suspected is newer than 1.7.2 (6379). (Because 6442 is greater than 6379).

The Latest built is 6451. Apparently larger than yours.

https://github.com/LSPosed/LSPosed/actions/runs/1932947734

**Comment by yujincheng08** [comment]
> I would have thought this is a usage issue which is why I'm providing logs from manager.

Manager will provide a log in zip format. And you are providing log from Magisk. Magisk is NOT manager.

**Comment by shaunkleyn** [comment]
> > I'm using 1.7.2 (6442) which I suspected is newer than 1.7.2 (6379). (Because 6442 is greater than 6379).
> 
> The Latest built is 6451. Apparently larger than yours.
> 
> https://github.com/LSPosed/LSPosed/actions/runs/1932947734

Thank you.  Perhaps add that link to the issue template so that users can find it.  This is what I was looking at: https://github.com/LSPosed/LSPosed/releases

**Comment by shaunkleyn** [comment]
Thanks for clearing up some of the unclarities and your help

**Comment by yujincheng08** [comment]
> No modules need to be installed for this behavior but these are the modules I have installed:

When you mention it, have you disabled all modules and see if this issue persists.

> Zygisk LSPosed
When you mention it, have you tested the riru version?

**Comment by shaunkleyn** [comment]
> > No modules need to be installed for this behavior but these are the modules I have installed:
> 
> When you mention it, have you disabled all modules and see if this issue persists.
> 

Yes, I have disabled all modules to check that it's not a specific module causing the issue.


> > Zygisk LSPosed
> > When you mention it, have you tested the riru version?

No, I'm specifically using Zygisk to use the "Deny list".  Magisk showed a message that Riru is not supported because Zygisk is enabled.

**Comment by shaunkleyn** [comment]
I know this ticket is closed but if you require it for future referenec, here's the log saved from the LSPosed Debug version: [LSPosed_2022-03-05T12_27_14.244.zip](https://github.com/LSPosed/LSPosed/files/8190460/LSPosed_2022-03-05T12_27_14.244.zip)

![1646476404583](https://user-images.githubusercontent.com/10231893/156879543-b4a0addc-50c2-47b1-9727-f73c5f7442a6.jpg)

**Comment by yujincheng08** [comment]
Grab a log without any xposed module?

**Comment by shaunkleyn** [comment]
I disabled all modules in Magisk and LSPosed and pulled this log. (The issue with the space between GBoard and the bottom of the screen was still there)
[LSPosed_2022-03-05T14_27_26.852_all modules_disabled.zip](https://github.com/LSPosed/LSPosed/files/8190676/LSPosed_2022-03-05T14_27_26.852_all.modules_disabled.zip)

I uninstalled all LSPosed modules and pulled this log.  The space issue persisted.
[LSPosed_2022-03-05T14_40_23.051_all_lsposed_modules_uninstalled.zip](https://github.com/LSPosed/LSPosed/files/8190678/LSPosed_2022-03-05T14_40_23.051_all_lsposed_modules_uninstalled.zip)
<img width="360" alt="Screenshot_20220305-144312_Pixel Launcher_1" src="https://user-images.githubusercontent.com/10231893/156883833-d0122835-2ef0-49ff-8feb-0c466786c77a.png">


I disabled Zygisk LSPosed in Magisk and the space issue was resolved.
<img width="360" alt="Screenshot_20220305-144447_Pixel Launcher_1" src="https://user-images.githubusercontent.com/10231893/156883839-59d51a07-eb3e-43b2-a198-e33b78d1bcc1.png">

**Comment by shaunkleyn** [comment]
Should I recreate the bug ticket?

**Comment by yujincheng08** [comment]
Can you try riru version? just temporarily disable zygisk for one boot.

**Comment by shaunkleyn** [comment]
> Can you try riru version? just temporarily disable zygisk for one boot.

No problem.  I'll do so and send you the logs.

**Comment by shaunkleyn** [comment]
So with Riru everything's fine.  No spacing issue.  Here are logs if you need them.  One where all modules were enabled and one where I disabled all of them.  There was no issue even with the modules enabled.
[LSPosed_2022-03-05T16_42_32.678_riru_lsposed_modules_enabled.zip](https://github.com/LSPosed/LSPosed/files/8190869/LSPosed_2022-03-05T16_42_32.678_riru_lsposed_modules_enabled.zip)
[LSPosed_2022-03-05T16_45_06.590_riru_lsposed_modules_disabled.zip](https://github.com/LSPosed/LSPosed/files/8190870/LSPosed_2022-03-05T16_45_06.590_riru_lsposed_modules_disabled.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8191190/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Will this build cause the issue?

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8191190/LSPosed-v1.7.2-6451-zygisk-debug.zip) Will this build cause the issue?

Yes, it's the same build I'm currently using and it still has the spacing issue.  I installed it this morning after you sent me the link to the CI builds.

**Comment by yujincheng08** [comment]
not the same. i did some modification that may fix this issue. i didnt increase the version tho.

**Comment by shaunkleyn** [comment]
> not the same. i did some modification that may fix this issue. i didnt increase the version tho.

> 

Oh, my apologies.  I downloaded it and tried it now.  It still has the same issue.  I'm attaching the log in case you need it.
[LSPosed_2022-03-05T21_46_38.609.zip](https://github.com/LSPosed/LSPosed/files/8191349/LSPosed_2022-03-05T21_46_38.609.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8191950/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this. I disabled all funtionality and basically it will do nothing.

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8191950/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this. I disabled all funtionality and basically it will do nothing.

👍This one resolves the space issue.  I just can't attach any logs because the LSPosed app doesn't open (probably because all functionality has been disabled).

**Comment by yujincheng08** [comment]
Ok. I will try to enable some of the functionality and see which line of code causes the problem.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192599/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Try this.

**Comment by shaunkleyn** [comment]
> 

No problem. It's not urgent - whenever you have time to do it.  Thank you for helping.

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192599/LSPosed-v1.7.2-6451-zygisk-debug.zip) Try this.

No issues with this build.  Spacing is perfect.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192637/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192637/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

This one has the spacing issue again.

**Comment by yujincheng08** [comment]
can you try to disable zygisk-lsposed and install zygisk-sui and see if the same result issue happens?

**Comment by shaunkleyn** [comment]
> can you try to disable zygisk-lsposed and install zygisk-sui and see if the same result issue happens?

I installed this zygisk-sui version and there's no spacing issue with it: https://github.com/RikkaApps/Sui/releases/download/v12.6.1/sui-zygisk-v12.6.1-release.zip

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192658/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this?

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192658/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this?

No issue with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192687/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192687/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

The issue is back with this one

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192698/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192698/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

No spacing issue with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192709/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192709/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

Still no spacing issue with this one. :)

**Comment by yujincheng08** [comment]
Should be caused by this line:
https://github.com/LSPosed/LSPosed/blob/dc6a599f00336270df52425a15eaa2462c8be5eb/core/src/main/cpp/main/src/context.cpp#L197

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192717/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> Should be caused by this line:
> 
> https://github.com/LSPosed/LSPosed/blob/dc6a599f00336270df52425a15eaa2462c8be5eb/core/src/main/cpp/main/src/context.cpp#L197

I don't know anything about Android development or C++ but it's weird that that would cause it because I would have suspected it to be something that would be linked to UI or GBoard or keyboard or something like that.

> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192717/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Weird - the spacing issue is back with this one. :(

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192734/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192734/LSPosed-v1.7.2-6451-zygisk-debug.zip)

No spacing issue.  It's resolved with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192747/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192747/LSPosed-v1.7.2-6451-zygisk-debug.zip)

No issue with this one 👍

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192778/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192778/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue is back with this one.

**Comment by shaunkleyn** [comment]
Does it appear to be an intermitted issue that sometimes happens and sometimes it doesn't or can you see a pattern?

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192798/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192798/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue seems to be fixed again with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192802/LSPosed-v1.7.2-6451-zygisk-debug.zip)
And this will bring back the issue?

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192802/LSPosed-v1.7.2-6451-zygisk-debug.zip) And this will bring back the issue?

Yes, the issue is back with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192815/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Will this issue persists in this build?

**Comment by yujincheng08** [comment]
Never mind. Try this:
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192841/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192815/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> Will this issue persists in this build?

Sorry for the delayed response. No, with this build the spacing seems to be fine.

**Comment by shaunkleyn** [comment]
> Never mind. Try this: [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192841/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Let me try this one quick..

**Comment by shaunkleyn** [comment]
> Never mind. Try this: [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192841/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Yes, with this one there is still an issue with the spacing.

**Comment by yujincheng08** [comment]
> > Never mind. Try this: [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192841/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> 
> Yes, with this one there is still an issue with the spacing.

This build basically did nothing. It is just loaded by Magisk and did nothing else.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192856/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> > > Never mind. Try this: [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192841/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> > 
> > 
> > Yes, with this one there is still an issue with the spacing.
> 
> This build basically did nothing. It is just loaded by Magisk and did nothing else.

Does that mean this might be an inconsistent issue?

> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192856/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this
Yeah, this one also brings back the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192864/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192864/LSPosed-v1.7.2-6451-zygisk-debug.zip)

This one still has the spacing issue.

**Comment by shaunkleyn** [comment]
> > [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192864/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> 
> This one still has the spacing issue.

Although, it does say "Zygisk module not loaded due to incompatitbility"

**Comment by yujincheng08** [comment]
That build is not even a zygisk module. How comes this problem exists.

**Comment by yujincheng08** [comment]
Can you try to remove `/data/adb/zygisk_lsposed/zygisk` folder and see if the issue exists?

**Comment by shaunkleyn** [comment]
> That build is not even a zygisk module. How comes this problem exists.

No idea. 

> Can you try to remove `/data/adb/zygisk_lsposed/zygisk` folder and see if the issue exists?

I removed the folder but left the last build installed.  The spacing issue is still there but the "Zygisk module not loaded due to incompatitbility" message is gone.

**Comment by yujincheng08** [comment]
Try to remove all .sh files in `/data/adb/zygisk_lsposed/zygisk`

**Comment by shaunkleyn** [comment]
> Try to remove all .sh files in `/data/adb/zygisk_lsposed/zygisk`

Just to check, my folder location is  `/data/adb/**modules**/zygisk_lsposed/zygisk`.  I removed all the .sh files and now the spacing is back to normal.  No spacing issue.

**Comment by yujincheng08** [comment]
Install my last build.
Reboot.
In `zygisk_lsposed` folder, there's a file named daemon, remove the line:

`mount tmpfs -t tmpfs /data/resource-cache`

and see if the issue persists.

**Comment by shaunkleyn** [comment]
> Install my last build. Reboot. In `zygisk_lsposed` folder, there's a file named daemon, remove the line:
> 
> `mount tmpfs -t tmpfs /data/resource-cache`
> 
> and see if the issue persists.

No problem.  Let me do that quick...

**Comment by shaunkleyn** [comment]
> > Install my last build. Reboot. In `zygisk_lsposed` folder, there's a file named daemon, remove the line:
> > `mount tmpfs -t tmpfs /data/resource-cache`
> > and see if the issue persists.
> 
> No problem. Let me do that quick...

Yeah, the issue is still there.

**Comment by yujincheng08** [comment]
How about removing the line
```
exec /system/bin/app_process ...
```

**Comment by shaunkleyn** [comment]
BUT, your last build has that message that says it's incompatible.  Should I delete the `zygisk` folder again?

**Comment by yujincheng08** [comment]
no need. the problem is from those .sh files.

**Comment by shaunkleyn** [comment]
> How about removing the line
> 
> ```
> exec /system/bin/app_process ...
> ```

So this seems to resolve the issue

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192917/LSPosed-v1.7.2-6451-zygisk-debug.zip)
try this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192917/LSPosed-v1.7.2-6451-zygisk-debug.zip) try this

No unfortunately this brings back the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192926/LSPosed-v1.7.2-6451-zygisk-debug.zip)
How about this

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192926/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

I'm busy trying this one.  In the meantime, do I need to Remove the module from Magisk, reboot, install the new one and reboot again every time or can I just install every module over the existing one (without removing it from Magisk and rebooting first)

**Comment by yujincheng08** [comment]
Replacing the existing one and reboot is enough

**Comment by shaunkleyn** [comment]
> Replacing the existing one and reboot is enough

Cool!  That should speed things up a bit.

> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192926/LSPosed-v1.7.2-6451-zygisk-debug.zip) How about this

Yeah, this one also still has the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192943/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192943/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue persists with this one as well.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192947/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192947/LSPosed-v1.7.2-6451-zygisk-debug.zip)

I'm surprised you haven't given up yet.  Thank you :)

The issue seems to be resolved with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192958/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Never gonna give you up
Never gonna let you down

**Comment by shaunkleyn** [comment]
> Never gonna give you up
> Never gonna let you down
🎵🎵🎵🎵🎵🎵Never gonna run around and desert you🎵🎵🎵🎵🎵🎵🤣

The issue is back with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192996/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8192996/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> 

This one gives me the following:

![Screenshot_20220306-182601_Magisk.png](https://user-images.githubusercontent.com/10231893/156932074-4f757e55-2ceb-4efe-b3f5-266d007a620a.png)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193001/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193001/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue is resolved with this one

**Comment by yujincheng08** [comment]
Can you check if there's still a process named `lspd`?

**Comment by shaunkleyn** [comment]
> Can you check if there's still a process named `lspd`?

I'm not sure where to check that.  I checked "Running Services" under Developer Options but can't see it there.  The LSPosed app also doesn't open.

**Comment by yujincheng08** [comment]
check the result of command `su -c ps -A | grep lspd`

**Comment by shaunkleyn** [comment]
> check the result of command `su -c ps -A | grep lspd`

Thank you 😄

Seems like it is. 
![Screenshot_20220306-183757_Termux.png](https://user-images.githubusercontent.com/10231893/156932625-118acb27-e6ef-47f4-9f5f-a6fdbea51e0a.png)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193031/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193031/LSPosed-v1.7.2-6451-zygisk-debug.zip)

This one returns the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193043/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193043/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Same spacing issue with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193061/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193061/LSPosed-v1.7.2-6451-zygisk-debug.zip)

This one also has the issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193079/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193079/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue persists with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193090/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193090/LSPosed-v1.7.2-6451-zygisk-debug.zip)

The issue is resolved with this build.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193111/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8193111/LSPosed-v1.7.2-6451-zygisk-debug.zip)

No issue on this one either.  Spacing is perfect.

It's getting a bit late on this side of the world, bud so I'll try to test the next build tomorrow sometime.  Thank you for dedicating your time to this.  I greatly appreciate it. :)  

Enjoy the rest of your day / night.

**Comment by yujincheng08** [comment]
Luckily we found the issue. I am in UTC+8 so it's late for me as well. Just use this build for now. It should work with full funtionality.

**Comment by shaunkleyn** [comment]
> Luckily we found the issue. I am in UTC+8 so it's late for me as well. Just use this build for now. It should work with full funtionality.

I'm so glad you managed to identify the cause of it. 

I just quickly wanted to let you know that it looks like the last build might be breaking Zygisk. When I install it I get the following message even though Zygisk is enabled. When I uninstall the module the message disappears.

![Screenshot_20220306-193223_Magisk.png](https://user-images.githubusercontent.com/10231893/156934864-1f318d03-be2d-4de2-8641-cf7329255c4e.png)

![Screenshot_20220306-193251_Magisk.png](https://user-images.githubusercontent.com/10231893/156934865-af136b63-9c7d-4032-918e-e3f7e3bfa353.png)

**Comment by yujincheng08** [comment]
[riru-v26.1.4.r239.125daf3f89-debug.zip](https://github.com/LSPosed/LSPosed/files/8193986/riru-v26.1.4.r239.125daf3f89-debug.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194331/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194331/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Good morning. :)

This one returns the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194966/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194966/LSPosed-v1.7.2-6451-zygisk-debug.zip)
> 

![Screenshot_20220307-070814_Magisk.png](https://user-images.githubusercontent.com/10231893/156971594-a0924536-4217-4634-82d5-74f600c8de5b.png)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194977/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8194977/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Still has the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195003/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195003/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Still has the spacing issue.

**Comment by yujincheng08** [comment]
I think this issue is OnePlus specific. We used to face the same problem in Riru but it's fixed by simply unsharing our daemon. However, this does not work in Zygisk. We need more investigation.

**Comment by shaunkleyn** [comment]
> s issue is OnePlus specific. We used to face the same problem in Riru but it's fixed by simply unsharing our daemon. However, this does not work in Zygisk. We need more investigation

No problem. It's not like it's breaking anything.  it's just a spacing issue so I can live with it.

Thank you for looking into this. :)

**Comment by yujincheng08** [comment]
Can you try riru 26.0.5: https://github.com/RikkaApps/Riru/releases/tag/v26.0.5
And install riru lsposed and see if the problem persists?

**Comment by shaunkleyn** [comment]
> Can you try riru 26.0.5: https://github.com/RikkaApps/Riru/releases/tag/v26.0.5 And install riru lsposed and see if the problem persists?

Yeah, the issue persists with this one.  I used Riru - LSPosed v1.7.2 (6451) with this.
[LSPosed_2022-03-07T07_35_31.381.zip](https://github.com/LSPosed/LSPosed/files/8195120/LSPosed_2022-03-07T07_35_31.381.zip)

**Comment by yujincheng08** [comment]
And [26.1.0](https://github.com/RikkaApps/Riru/releases/tag/v26.1.0) will suppress this issue, right?

**Comment by shaunkleyn** [comment]
> And [26.1.0](https://github.com/RikkaApps/Riru/releases/tag/v26.1.0) will suppress this issue, right?

That's correct.  This one resolves the issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195139/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Install it, reboot and send `/data/adb/lspd/trace`

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195139/LSPosed-v1.7.2-6451-zygisk-debug.zip) Install it, reboot and send `/data/adb/lspd/trace`

No problem.  Here it is.
[trace.zip](https://github.com/LSPosed/LSPosed/files/8195189/trace.zip)


I do however see the "Zygisk module not loaded message".
![Screenshot_20220307-075418_Magisk](https://user-images.githubusercontent.com/10231893/156976182-9c92d393-a248-4fd3-87b1-35cc31badbe9.png)

**Comment by yujincheng08** [comment]
Is your system has `/system/bin/strace`?

**Comment by shaunkleyn** [comment]
> Is your system has `/system/bin/strace`?

No, it has the following in the bin folder:

```
lemonadep:/system/bin $ ls
ls
[                          hostname                    racoon
abb                        hw                          readelf
abx                        hwclock                     readlink
abx2xml                    hwservicemanager            realpath
acc                        i2cdetect                   reboot
acca                       i2cdump                     recovery-persist
accd                       i2cget                      recovery-refresh
accd,                      i2cset                      renice
accd.                      iconv                       requestsync
acpi                       id                          resetprop
am                         idmap2                      resize.f2fs
apexd                      idmap2d                     resize2fs
app_process                ifconfig                    restorecon
app_process32              ime                         rm
app_process64              incident                    rmdir
appops                     incident-helper-cmd         rmmod
appwidget                  incident_helper             rss_hwm_reset
atrace                     incidentd                   rtcwake
audioserver                init                        run-as
auditctl                   inotifyd                    runcon
awk                        input                       schedtest
backuptool_ab.functions    insmod                      screencap
backuptool_ab.sh           install                     screenrecord
backuptool_postinstall.sh  installd                    sdcard
badblocks                  ionice                      secdiscard
base64                     iorap.cmd.compiler          secilc
basename                   iorap.cmd.maintenance       sed
bc                         iorap.inode2filename        sendevent
bcc                        iorap.prefetcherd           sensorservice
blank_screen               iorapd                      seq
blkid                      iorenice                    service
blockdev                   ip                          servicemanager
bmgr                       ip-wrapper-1.0              set-verity-state
bootanimation              ip6tables                   setcap
bootstat                   ip6tables-restore           setenforce
bootstrap                  ip6tables-save              setprop
boringssl_self_test32      ip6tables-wrapper-1.0       setsid
boringssl_self_test64      iptables                    settings
bpfloader                  iptables-restore            sgdisk
bu                         iptables-save               sh
bugreport                  iptables-wrapper-1.0        sha1sum
bugreportz                 keystore2                   sha224sum
bunzip2                    keystore_cli_v2             sha256sum
bzcat                      kill                        sha384sum
bzip2                      killall                     sha512sum
cal                        ld.mc                       showmap
cameraserver               ldd                         simpleperf
cat                        librank                     simpleperf_app_runner
charger                    linker                      sleep
chattr                     linker64                    sload_f2fs
chcon                      linker_asan                 sm
chgrp                      linker_asan64               snapshotctl
chmod                      linkerconfig                snapuserd
chown                      llkd                        sort
chroot                     lmkd                        split
chrt                       ln                          sqlite3
cksum                      load_policy                 ss
clatd                      locksettings                start
clear                      log                         stat
cmd                        logcat                      stop
cmp                        logd                        storaged
comm                       logname                     strings
content                    logwrapper                  stty
cp                         losetup                     su
cpio                       lpdump                      supolicy
credstore                  lpdumpd                     surfaceflinger
curl                       ls                          svc
cut                        lsattr                      swapoff
dalvikvm                   lshal                       swapon
date                       lsmod                       sync
dd                         lsof                        sysctl
debuggerd                  lspci                       tac
defrag.f2fs                lsusb                       tail
device_config              magisk                      tar
devmem                     magiskinit                  taskset
dex2oat                    magiskpolicy                tc
df                         make_f2fs                   tc-wrapper-1.0
diff                       md5sum                      tcpdump
dirname                    mdnsd                       tee
disable-verity             mediaextractor              telecom
djs,                       mediametrics                test
djs-config                 mediaserver                 time
djs-daemon                 microcom                    timeout
djs-status                 migrate_legacy_obb_data.sh  tombstoned
djs-stop                   mini-keyctl                 toolbox
djs-version                mkdir                       top
djs.                       mke2fs                      touch
djsc                       mkfifo                      toybox
djsd                       mkfs.exfat                  tr
djsv                       mkfs.ext2                   traced
dmabuf_dump                mkfs.ext3                   traced_perf
dmctl                      mkfs.ext4                   traced_probes
dmesg                      mkfs.ntfs                   trigger_perfetto
dnsmasq                    mknod                       true
dos2unix                   mkswap                      truncate
dpm                        mktemp                      tty
drmserver                  mm_events                   tune2fs
du                         modinfo                     tzdatacheck
dump.f2fs                  modprobe                    ueventd
dumpstate                  monkey                      uiautomator
dumpsys                    more                        uinput
e2freefrag                 mount                       ulimit
e2fsck                     mount.ntfs                  umount
e2fsdroid                  mountpoint                  uname
echo                       mtpd                        uncrypt
egrep                      mv                          uniq
enable-verity              nc                          unix2dos
env                        ndc                         unlink
expand                     ndc-wrapper-1.0             unshare
expr                       netcat                      unzip
fallocate                  netd                        update_engine
false                      netstat                     update_verifier
fgrep                      netutils-wrapper-1.0        uptime
file                       newfs_msdos                 usbd
find                       nice                        usleep
flags_health_check         nl                          uudecode
flock                      nohup                       uuencode
fmt                        nproc                       uuidgen
free                       nsenter                     vdc
fsck.exfat                 od                          viewcompiler
fsck.f2fs                  odsign                      vmstat
fsck.ntfs                  otapreopt                   vold
fsck_msdos                 otapreopt_chroot            vold_prepare_subdirs
fsverity_init              otapreopt_script            vr
fsync                      otapreopt_slot              wait_for_keymaster
gatekeeperd                paste                       watch
getcap                     patch                       watchdogd
getconf                    perfetto                    wc
getenforce                 pgrep                       which
getevent                   pidof                       whoami
getprop                    ping                        wificond
gpuservice                 ping6                       wm
grep                       pkill                       xargs
groups                     pm                          xml2abx
gsi_tool                   pmap                        xxd
gsid                       pppd                        yes
gunzip                     printenv                    zcat
gzip                       printf                      zipinfo
head                       procrank                    ziptool
heapprofd                  ps
hid                        pwd
```

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195235/LSPosed-v1.7.2-6451-zygisk-debug.zip)
Use this to grab `/data/adb/lspd/trace` again.

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195235/LSPosed-v1.7.2-6451-zygisk-debug.zip) Use this to grab `/data/adb/lspd/trace` again.

This one looks better.  Here it is.:
[trace.zip](https://github.com/LSPosed/LSPosed/files/8195261/trace.zip)

**Comment by yujincheng08** [comment]
Is this build has the same spacing issue?

**Comment by shaunkleyn** [comment]
No this one seem to have resolved the spacing issue.

**Comment by shaunkleyn** [comment]
> No this one seem to have resolved the spacing issue.

Not sure if it is due to this message showing up again:
![Screenshot_20220307-075418_Magisk](https://user-images.githubusercontent.com/10231893/156978737-7c2f8a7d-2b1f-44a3-abdd-4ab3b537c23f.png)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195297/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195297/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Same result as the previous one.  Spacing is fine but "Zygisk module not loaded".  I removed LSPosed from Magisk, rebooted, installed the build you sent and rebooted again.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195356/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195356/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Nope, same result.  Perfect spacing but "Zygisk module not loaded".  I do have "Universal Safetynet Fix" which is also a Zygisk module and that one's loading fine.

![Screenshot_20220307-083900_Magisk_1](https://user-images.githubusercontent.com/10231893/156980981-a6921e01-3040-483a-b349-d0bdcac9c4fa.png)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195396/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195396/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded fine with this one.  Spacing issue also resolved.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195440/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195440/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded but spacing issue is back.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195471/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195471/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded but spacing issue is back.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195496/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195496/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded but still has the spacing issue.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195519/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195519/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded fine.  The spacing issue is resolved with this one.

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195866/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195866/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Module loaded and spacing issue resolved :) :)

**Comment by yujincheng08** [comment]
[LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195921/LSPosed-v1.7.2-6451-zygisk-debug.zip)

**Comment by shaunkleyn** [comment]
> [LSPosed-v1.7.2-6451-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8195921/LSPosed-v1.7.2-6451-zygisk-debug.zip)

Everything's still working (Module loaded & spacing resolved)

**Comment by yujincheng08** [comment]
Ok. Though we still don't know why and the solution is dirty. But it's fixed.

**Comment by shaunkleyn** [comment]
> Ok. Though we still don't know why and the solution is dirty. But it's fixed.

I suspected it's probably something weird causing it.  Thank you for looking into this and your time to do thorough testing with me.

**Comment by yujincheng08** [comment]
[Log Catcher-v22.5(27).zip](https://github.com/LSPosed/LSPosed/files/8195995/Log.Catcher-v22.5.27.zip)
BTW, can you grab a full bootlog using this module?

The log is saved to /cache/bootlog by default
If /cache does not exist, save to /data/local/bootlog

**Comment by shaunkleyn** [comment]
> [Log Catcher-v22.5(27).zip](https://github.com/LSPosed/LSPosed/files/8195995/Log.Catcher-v22.5.27.zip) BTW, can you grab a full bootlog using this module?
> 
> The log is saved to /cache/bootlog by default If /cache does not exist, save to /data/local/bootlog

I'll gladly do that for you.  Here it is.
[bootlog-2022-03-07-10-30-47.tar.gz](https://github.com/LSPosed/LSPosed/files/8196065/bootlog-2022-03-07-10-30-47.tar.gz)

**Comment by shaunkleyn** [comment]
> > [Log Catcher-v22.5(27).zip](https://github.com/LSPosed/LSPosed/files/8195995/Log.Catcher-v22.5.27.zip) BTW, can you grab a full bootlog using this module?
> > The log is saved to /cache/bootlog by default If /cache does not exist, save to /data/local/bootlog
> 
> I'll gladly do that for you. Here it is. [bootlog-2022-03-07-10-30-47.tar.gz](https://github.com/LSPosed/LSPosed/files/8196065/bootlog-2022-03-07-10-30-47.tar.gz)

Sorry, I think I attached the wrong file.  I'm attaching the correct one shortly.

**Comment by shaunkleyn** [comment]
> [Log Catcher-v22.5(27).zip](https://github.com/LSPosed/LSPosed/files/8195995/Log.Catcher-v22.5.27.zip) BTW, can you grab a full bootlog using this module?
> 
> The log is saved to /cache/bootlog by default If /cache does not exist, save to /data/local/bootlog

Here's the log file I got from /cache/bootlog: 
[boot-2022-03-07-10-30-47.log](https://github.com/LSPosed/LSPosed/files/8196082/boot-2022-03-07-10-30-47.log)
